### ISSUE TITLE
EndOf File Error

### ISSUE THREAD

**Issue by ecmnet** [caplogic/Mappedbus#1]
Hi,
one question: After a certain time, the MessageWriter quits with 'end of file'. It seems, that a wrap around is not implemented. Is that correct?

**Comment by caplogic** [comment]
That's correct and by design since the idea with mappedbus is to store all messages. So you'll have to make the file large enough for your use. However, an improvement could be that the writers continue to another file when the first one is full.

**Comment by samrajcse** [comment]
Any update on the feature request?
