### ISSUE TITLE
Why is there a sleep in this example? Is this safe?

### ISSUE THREAD

**Issue by mcqueenorama** [caplogic/Mappedbus#3]
I see a sleep here:

https://github.com/caplogic/Mappedbus/blob/master/src/sample/io/mappedbus/sample/object/ObjectWriter.java#L23

It makes me worry about if this is safe for independent reads/writes.

**Comment by caplogic** [comment]
That sleep is only for demonstration purposes when running that sample program. Independent read/writes work fine which is shown in the tests.
