### ISSUE TITLE
Publish artifacts to Maven Central

### ISSUE THREAD

**Issue by jjzazuet** [caplogic/Mappedbus#4]
Hi. Do you guys have jars for Mappedbus available in Maven central?

Thanks!

**Comment by caplogic** [comment]
Hi! It's not published at Maven central at the moment.

**Comment by jjzazuet** [comment]
Third party projects can manage their dependencies better when they're available in an artifact repository such as Maven central or Bintray.

Is there a particular reason stopping this project from sharing artifacts?

Thanks for your time!

**Comment by ajermakovics** [comment]
Hi all,

It is possible to get Mappedbus as a Gradle/Maven dependency using jitpack: https://jitpack.io/#caplogic/Mappedbus/v0.5

Happy to submit a PR to add this info to readme @caplogic is interested
