### ISSUE TITLE
Contact email

### ISSUE THREAD

**Issue by heitorfm** [caplogic/Mappedbus#5]
Hi sorry to use this channel, but i did not find other.
I´ve trying to reach you by email, but its keep bouncing back.

============================================
This is an automatically generated Delivery Status Notification
THIS IS A WARNING MESSAGE ONLY.
YOU DO NOT NEED TO RESEND YOUR MESSAGE.
Delivery to the following recipient has been delayed:

     info@mappedbus.io

Message will be retried for 0 more day(s)

Technical details of temporary failure:
DNS Error: 5160217 DNS type 'mx' lookup of mappedbus.io responded with code NOERROR
5160217 DNS type 'aaaa' lookup of mappedbus-io.mail.protection.outlook.com. responded with code NXDOMAIN
5160217 DNS type 'a' lookup of mappedbus-io.mail.protection.outlook.com. responded with code NXDOMAIN

**Comment by caplogic** [comment]
While I fix the primary contact email, can you please send a mail to mappedbus@gmail.com instead?
