### ISSUE TITLE
Reader get stunk on mem.getLongVolatile when calling next()

### ISSUE THREAD

**Issue by bizzard4** [caplogic/Mappedbus#7]
I can run sample using Object fine, bu I can't seem to be able to implement the same on my own project.

My reader next() function always return false on 
`
if (mem.getLongVolatile(Structure.Limit) <= limit) {
return false;
}
`

I am not sure what is the purpose of this function and also I can't seem to figure out why my project is different than the sample.

My project create the Reader and Writer in the same process.

**Comment by caplogic** [comment]
That's the check to see if anything has been written to the file.  Have you called the write method on writer to the same file?
If you send a minimal test code showing your issue I'll check.

**Comment by bizzard4** [comment]
Finally my problem was how I implemented the writer, I was not updating position (pos +4, pos + 8, etc.). Shame *bell* Shame *bell*
