### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by LucaGabi** [caplogic/Mappedbus#9]
I would need help and I thought to ask here: can I somehow share a memory space to write from a mono application to a java application (with synchronisation clearly) ?

Thanks.

**Comment by caplogic** [comment]
If the same mechanisms as in Java's Unsafe class (volatile read/write, fetch-and-increment, and compare-and-swap on a memory mapped file) are available in .NET/C# then I suppose you could do it in theory.  It's not a goal for this project though.
